version: "3"
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: price_tracker_api
    user: "${UID}:${GID}"
    command: sleep infinity
    volumes:
      - ./backend:/app
    environment:
      - UID=${UID}
      - GID=${GID}
    depends_on:
      - db
    ports:
      - "8393:8393"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: price_tracker_frontend
    volumes:
      - ./frontend:/app
    command: sleep infinity
    depends_on:
      - api
      - scraper
    ports:
      - "3000:3000"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: pricetracker
      POSTGRES_PASSWORD: example
    volumes:
      - price_tracker_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  scraper:
    build:
      context: ./scraper
      dockerfile: Dockerfile
    image: price_tracker_scraper
    command: sleep infinity
    volumes:
      - ./scraper:/app
    depends_on:
      - api
      - db
    ports:
      - "3001:3001"

  adminer:
    image: adminer
    restart: always
    ports:
      - "3002:8080"
#  nginx:
#    image: nginx
#    restart: always
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - "8080:80"


volumes:
  price_tracker_db:
